version: 2.1

orbs:
  kicadcd: mundodisco8/kicadcd@0.1.0

workflows:
  createFabricationOutputsAndStore:
      jobs:
        - kicad-manufacturing-files/initialSetup:
            name: Initial Setup
        - kicad-manufacturing-files/pickAndPlacePositions:
            name: Get Pick And Place Positions # best practice is to name each orb job
            projectPath: PROJECT_PATH
            PCBFile: "Calavera.kicad_pcb"
            includeVirtualComponentsFlag: false
            artifactsPath: "artifacts/"
            requires:
              - Initial Setup

        - kicad-manufacturing-files/gerberFiles:
            name: Generate Gerber files
            projectPath: PROJECT_PATH
            PCBFile: "Calavera.kicad_pcb"
            configFile: "Kiplot_config.yaml"
            artifactsPath: "artifacts/"
            requires:
              - Initial Setup

# - kicad-manufacturing-files/storeArtifacts:
#     artifactsPath: artifacts
#     requires:
#       - Get Pick And Place Positions
#       - Generate Gerber files
