version: 2.1

orbs:
  kicadcd: mundodisco8/kicad-manufacturing-files@dev:06_11_19

workflows:
  createFabricationOutputsAndStore:
      jobs:
        - kicadcd/initialSetup:
            name: Initial Setup
        - kicadcd/pickAndPlacePositions:
            name: Get Pick And Place Positions # best practice is to name each orb job
            projectPath: PROJECT_PATH
            PCBFile: "helix.kicad_pcb"
            includeVirtualComponentsFlag: false
            artifactsPath: "/root/project/artifacts/"
            requires:
              - Initial Setup

        - kicadcd/gerberFiles:
            name: Generate Gerber files
            projectPath: PROJECT_PATH
            PCBFile: "helix.kicad_pcb"
            configFile: "Kiplot_config.yaml"
            artifactsPath: "/root/project/artifacts/"
            requires:
              - Initial Setup


# - kicad-manufacturing-files/storeArtifacts:
#     artifactsPath: artifacts
#     requires:
#       - Get Pick And Place Positions
#       - Generate Gerber files
